language: java
jdk:
- oraclejdk8
before_script:
- if [[ $TRAVIS_COMMIT_MESSAGE == *"[ci-ext]"* ]]; then bash
  updateCleanVersion.sh --emulation-mode; mv mooltipass-extension.zip ./sauce_labs_tests/chrome_extension.crx;
  cd ./sauce_labs_tests; fi;
env:
  matrix:
  - TEST_SUITE=Tests.feature
  global:
  - SAUCE_USERNAME: mooltipass
script:
- if [[ $TRAVIS_COMMIT_MESSAGE == *"[ci-ext-quiet]"* ]]; then mvn clean install -q -Dcucumber.options="src/test/resources/mooltipass/automatedTests/features/$TEST_SUITE"; fi;
  if [[ $TRAVIS_COMMIT_MESSAGE == *"[ci-ext]"* ]]; then mvn clean test -Dcucumber.options="src/test/resources/mooltipass/automatedTests/features/$TEST_SUITE"; fi;
